### ISSUE TITLE
Variables display and forms layout

### ISSUE THREAD

**Issue by grgrgrknght** [grgrgrknght/facet3d-viewer-issues#1]
1. Change FileOptionsForm title to "Variable Options"
2. (If possible) Only show variables that are available (have results in this file) in the drop down boxes. Also limit variables in Select Contours to Display form.
3. Make all button tooltips match the menu text, i.e. "Variable Options"
4. Add the button icon to the menu item (comment applies to all menu items)
5. Make Menu Like Below

Tools
--Variable Options
Results
--Display Variables
--Query Window
View
--Recenter Window

Buttons order (L to R) should follow menu order.

6. Remove icon from Query form (none of the other forms have icons)

7. User file in zip is called Uzer?

8. Name main executable FACET3D View.exe Give it an icon (Probably the F3D icon with a big "V" overlaid on it - see attached).

9. See clean folder in my DT. You don't need most of the files you copied over to run.

10. Query form should remember position between close and open. 

11. In query window change IPoint to Hit Point. Also, when I change to Excel the query window is still in front. It should be limited to the viewer only.

![facet3d_icon_medium_viewer](https://cloud.githubusercontent.com/assets/12447465/23188475/709639bc-f854-11e6-82c5-b1ec051a94e4.png)

**Comment by vsantalov** [comment]
For #5, what are "results" and "view"? I don't have those controls.

**Comment by grgrgrknght** [comment]
They are new menu items. I clarified the order above. My space indents were not previously coming through.

**Comment by grgrgrknght** [comment]
"Select contours to display" is one of your menu items that opens the form with the left/right panels.

**Comment by vsantalov** [comment]
All points addressed and updates pushed to master
