### ISSUE TITLE
Splash screen needed

### ISSUE THREAD

**Issue by grgrgrknght** [grgrgrknght/facet3d-viewer-issues#16]
Add a splash screen after main form open that has 

FACET3D View
BETA Version 0.0.X  (increment each release now that others are using the code)
Released YYYY-MM-DD (I know of no reliable way other than to hard code each release to get the build date, using reflection to get created date or modified date is not reliable. Try the mdb solution here.   https://stackoverflow.com/questions/1600962/displaying-the-build-date)  I also like the simpler solution on that page of simply adding a text file to the exe with the build date from a pre-compile command

Maybe a nice image also.
Set to disappear on click or 3 sec timer

**Comment by grgrgrknght** [comment]
This seems to work  

<Extension>
    Public Function GetLinkerTime(assembly As Reflection.Assembly, Optional target As TimeZoneInfo = Nothing) As DateTime
        'Usage:  Dim linkTimeLocal = Reflection.Assembly.GetExecutingAssembly().GetLinkerTime()
        Dim filePath = assembly.Location
        Const c_PeHeaderOffset As Integer = 60
        Const c_LinkerTimestampOffset As Integer = 8

        Dim buffer = New Byte(2047) {}

        Using stream = New FileStream(filePath, FileMode.Open, FileAccess.Read)
            stream.Read(buffer, 0, 2048)
        End Using

        Dim offset = BitConverter.ToInt32(buffer, c_PeHeaderOffset)
        Dim secondsSince1970 = BitConverter.ToInt32(buffer, offset + c_LinkerTimestampOffset)
        Dim epoch = New DateTime(1970, 1, 1, 0, 0, 0,
        DateTimeKind.Utc)

        Dim linkTimeUtc = epoch.AddSeconds(secondsSince1970)

        Dim tz = If(target, TimeZoneInfo.Local)
        Dim localTime = TimeZoneInfo.ConvertTimeFromUtc(linkTimeUtc, tz)

        Return localTime
    End Function

**Comment by vsantalov** [comment]
done and pushed to master
