### ISSUE TITLE
Change variable names in Display Variable window to User names

### ISSUE THREAD

**Issue by grgrgrknght** [grgrgrknght/facet3d-viewer-issues#25]
1. F3D now will not write a variable if it's calculate checkbox is checked. Just FYI. Also, renaming variables core name was too hard hence..

I'd like to try using the Display Name or User name for the variable in the 2 window selection form instead of the embedded name. If there is no display name use the embedded name.

**Comment by vsantalov** [comment]
This functionality already exists. I just tested it.

**Comment by vsantalov** [comment]
Pushed to master. Exe updated in data transfers.
