### ISSUE TITLE
Replace display variables form with another tree view

### ISSUE THREAD

**Issue by grgrgrknght** [grgrgrknght/facet3d-viewer-issues#26]
Roy brings up a good point that it is not intuitive to first select a display variable and then a scenario. 

I suggest removing the form and button and menu item and replacing with a tree view left of the Scenarios tree view that lists all the display variables (User names, not embedded names). No need for an "All" parent. Checkstate will trigger update.

This way the user flow is more like follow each tab: Variables, Scenarios, Geometry

Also, select all scenarios and geometry by default so as soon as they select a variable something shows up.

Let me know what you think.

**Comment by grgrgrknght** [comment]
You will have to rebuild the tree view after the user closes the Variable Options form since the names could have been changed.

**Comment by vsantalov** [comment]
Implemented all
