### ISSUE TITLE
Update to F3D export broke viewer

### ISSUE THREAD

**Issue by grgrgrknght** [grgrgrknght/facet3d-viewer-issues#28]
I rewrote the exporter to not write weather and leak size tree nodes for consequence assessments. Therefore, all the data is not under the scenario node but the viewer does not seem to work with this setup. Need to fix so that no assumptions are made when it comes to which level on the tree is the leaf node.

Test file
Z:\Data Transfers\GRK\FACET_VIEWER_BETA\F3D Viewer Testfiles\test_conseq.f3dv

Also, in F3D I added a leaksize property to consequence events under scenario objects. This value is used when writing the viewer leak size so you don't have to see NoLeakSize in the leaf node. Only written for QRA's.

**Comment by vsantalov** [comment]
The viewer now gets the leafnodes regardless of level. Works with arbitrary number of levels.
