### ISSUE TITLE
Shift click on buildings throws unhandled exception

### ISSUE THREAD

**Issue by grgrgrknght** [grgrgrknght/facet3d-viewer-issues#29]
Happens for variables other than pressure and impulse. Probably all variables that are not actually avail. on building surfaces.

**Comment by vsantalov** [comment]
Reproduced.

**Comment by vsantalov** [comment]
That is correct, querying for unavailable variables causes unhandled exception. How would you like me to present the outputs in this case? Facet gives all zeroes for all building components.

**Comment by grgrgrknght** [comment]
Don't report what is not avail. Just do nothing.

**Comment by vsantalov** [comment]
Addressed, pushed to master, updated exe.
