### ISSUE TITLE
Variable name in query window/window size/special % % bug

### ISSUE THREAD

**Issue by grgrgrknght** [grgrgrknght/facet3d-viewer-issues#30]
![image](https://user-images.githubusercontent.com/12447465/27242466-f9336a6c-52a2-11e7-8867-aff8e9b3b1eb.png)

**Comment by vsantalov** [comment]
Another potential solution might be to specify the variable unit with the variable name and remove the "Contour Value":
**JetFire ThermalLethality (% Lethality): 87.3%**
For ctrl+shift quarries that would mean specifying the unit only once for cleaner look:

**XY Plane Hit Point: [2699.05, 1420.02]
Pressure(psi);
MPL_01a	0.01
MPL_01b	0 
MPL_02a	0.3 
MPL_02b	0 
MPL_03a	0.34 
MPL_03b	0 
MPL_05	0** 

This way we also avoid special cases. What do you think?

**Comment by grgrgrknght** [comment]
I like your idea. Make it so.

**Comment by vsantalov** [comment]
All points addressed
