### ISSUE TITLE
Incorrect pressure reported

### ISSUE THREAD

**Issue by grgrgrknght** [grgrgrknght/facet3d-viewer-issues#4]
Using
Z:\Data Transfers\GRK\F3D Viewer Testfiles\test_conseq.f3dv
show pressure and query 01 - Office_b. Returns MAX 0.31 psi but a deep query does not give that pressure on the roof and based on the contours that is way too high.

Also, in the query window, put some (prefereably light gray) text that gives instructures on how to use. I'd suggest "Shift + click to query maximum values. CRLF Control + Shift + Click to open a report with all values."  After the first query delete this text and give result in black text.

**Comment by vsantalov** [comment]
addressed and pushed to master
