### ISSUE TITLE
Window position and persistence issues

### ISSUE THREAD

**Issue by grgrgrknght** [grgrgrknght/facet3d-viewer-issues#8]
On first show, place the Results window in the upper right corner of the canvas with a little canvas showing along the top and right edge.  

Result window text includes CRLF

Variables window started on my second monitor. I'd say always ensure this window is centered on the parent window.

Results window needs a right click context menu with a Clear All menuitem.

Clicking twice on Variable  or Display Variables will open 2 windows. Make these forms modal so you cannot do this (like version history window).

Clicking twice on results menu opens 2 windows. Since this one cannot be modal, you have to track whether it is already open. Possibly open from start and button just toggles visibility property of form.

**Comment by vsantalov** [comment]
All addressed. Pushed to master and exe updated
