### ISSUE TITLE
Mouse wheel zoom needs pan portion

### ISSUE THREAD

**Issue by grgrgrknght** [grgrgrknght/facet3d-viewer-issues#9]
Mouse wheel zoom should use mouse position relative to center of canvas to add a little pan for each zoom indent. Low priority.

**Comment by vsantalov** [comment]
There is something I was already experimenting with - google maps style zoom. The exe was updated with it. Check it out. Let me know if you like it.

**Comment by grgrgrknght** [comment]
I like it. It seems to give the same result when zooming away as F3D but zooming closer is different. I may have to copy this to F3D.

**Comment by vsantalov** [comment]
pushed to master
